name: PyInstaller

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
          generate_release_notes: false

  build:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Test
        run: |
          python test_renamer.py
      
      - name: Build
        run: |
          pyinstaller -F renamer.py -n Movie_Data_Renamer-CLI-${{ env.VERSION }}-${{ runner.os }}-amd64
        
      - name: Upload build artifact - ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: Movie_Data_Renamer-CLI-${{ env.VERSION }}-${{ runner.os }}-amd64
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: dist/*